### PR TITLE
fix(common): APPEX-512 dependency updates, support CJS and ESM default imports

### LINKED ISSUE #24: A few challenges
Package name seems to be `@bigcommerce/api-nodejs` not `bigcommerce-api-node`

When I try and instantiate a new `RestClient`
```
const bc = new BigCommerce.Rest({
    accessToken: process.env.ACCESS_TOKEN,
    storeHash: process.env.STORE_HASH
});
```
I get

 `TypeError: BigCommerce.RestClient is not a constructor`

### PR DESCRIPTION
**Pull request by bc-nekisham**
#### What?

Resolving open source issues

#### Tickets / Documentation

Fixes #24

cc @bigcommerce/gta-dt

### CODE REVIEW

**Comment by bc-nekisham** [comment]
The issue that was reported (on the import error) I realized was throwing the _non-constructor error_ when working with a JavaScript file not compiled from TypeScript. The BigCommerce object is working differently inside TS, letting you use BigCommerce.Rest() to create a new RestClient object. In JS, even while in a _cjs/ mjs_ file type it won’t work. We can update the ReadMe to add in the correct way to use the module inside a JS file which is using require `const BigCommerce = require("@bigcommerce/api-nodejs").default;` or I could update the index.ts file and have us export 0Auth and RestClient instead, with it only using the namespace export `export * from './types';` This would have the readme update to `import * as BigCommerce from '@bigcommerce/api-nodejs';` which works for both TS and JS projects.

**Review by matthewvolk — CHANGES_REQUESTED** [review]
I added "Fixes #24" to the PR description - be sure to add those changes we talked about into this PR before merging it so that we can close out the issue around importing in CommonJS vs. ES Modules

**Comment by bc-nekisham** [comment]
Updated with photos of require working for JS/CJS file type and import working for cjs/ts 
Screenshot 2023-05-22 at 4 38 57 PM
Screenshot 2023-05-22 at 4 38 57 PM
Screenshot 2023-05-22 at 8 56 44 PM

File: src/index.ts [hunk 1]
```diff
@@ -1,10 +1,11 @@
 import OAuth from './OAuth';
 import RestClient from './RestClient';
+import * as types from './types';
 
-const BigCommerce = {
-  Auth: OAuth,
-  Rest: RestClient,
-};
+class BigCommerce {
```
Comment (matthewvolk) [inline src/index.ts:5]: 🍹 This doesn't necessarily need to be a class - when you run `new BigCommerce.Auth`, the `BigCommerce.Auth` part still resolves to just `Auth` whether BigCommerce is a class or an object. I'd suggest talking with the team to see if there's any good reason to switch the object to a class

File: src/index.ts [hunk 2]
```diff
@@ -1,10 +1,11 @@
...
+  static Auth = OAuth;
+  static Rest = RestClient;
+  static Types = types;
```
Comment (matthewvolk) [inline src/index.ts:8]: 🍹 This might be outside the scope of this ticket - but I can't remember our original reason for exporting type definitions in general. The REST/OAuth methods are already typed when they're imported by consumers of the client, and we're not showing any demonstration of using the exported types in the README. I might suggest talking to the team about whether or not we actually want to explicitly export these.

Comment (bc-nekisham) [reply src/index.ts]: Updated this back to an object

File: src/index.ts (hunk 1 above)
Comment (bc-nekisham) [reply src/index.ts]: Updated back to obj

**Comment by bc-nekisham** [comment]
JS/ MJS/ CJS/ TS fiile imports and require for js js
mjs
cjs
ts

File: src/index.ts [hunk 3]
```diff
@@ -1,10 +1,11 @@
...
 
 const BigCommerce = {
   Auth: OAuth,
   Rest: RestClient,
+  Types: types,
 };
 
-export default BigCommerce;
-export * from './types';
+export = BigCommerce;
```
Comment (bc-chaz) [inline src/index.ts:11]: do we need to set a variable name here? @matthewvolk

Comment (matthewvolk) [reply src/index.ts:11]: No, the equal sign is important here. More info: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

> TypeScript supports `export =` to model the traditional CommonJS and AMD workflow.

File: src/index.ts (hunk 2 above)
Comment (matthewvolk) [reply src/index.ts]: We're still exporting types here - is there any good reason we should do this?

File: package.json [hunk 4]
```diff
@@ -24,9 +24,9 @@
     "url": "https://github.com/bigcommerce/bigcommerce-api-node.git"
   },
   "dependencies": {
-    "axios": "^0.26.1",
+    "axios": "^0.27.2",
     "form-data": "^4.0.0",
-    "jsonwebtoken": "^8.5.1"
+    "jsonwebtoken": "^9.0.0"
```
Comment (matthewvolk) [inline package.json:29]: There were a number of breaking changes between v8 and v9: 
> Breaking changes: See [Migration from v8 to v9](https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v8-to-v9)

Did you have a chance to confirm that our implementation is not affected?

Comment (bc-nekisham) [reply package.json:29]: This works.  I made this change with the prior closed PR I had for this ticket.

File: src/index.ts (hunk 2 above)
Comment (bc-nekisham) [reply src/index.ts]: Updated!

**Comment by bc-nekisham** [comment]
Updated js / ts 
typescript compiled
javascript file

**Review by matthewvolk — APPROVED** [review]
Thank you for your hard work on this one! 👍
